[package]
authors = ["Đăng Được <duoc200894@gmail.com>"]
edition = "2018"
name = "advanced_features"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
